# Generated by Django 5.2.9 on 2026-06-11 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_order_address_order_created_at_order_delivery_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('sales', 'Sales Report'), ('inventory', 'Inventory Report'), ('orders', 'Orders Report'), ('customers', 'Customer Report'), ('products', 'Product Report'), ('bestsellers', 'Best Sellers Report')], max_length=20),
        ),
    ]
