# Generated by Django 5.2.9 on 2026-06-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_orderitem_unit_price_at_purchase_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='checkout_request_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mpesa_receipt',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price_at_purchase',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
