# Generated by Django 5.2.9 on 2026-06-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
