# Generated by Django 5.2.9 on 2026-06-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
    ]
